5251 missing rule
openstax/ce-styles pull request #333
Opened 2023-10-16 21:56 UTC by jbwilson8

Issue: [I5251](https://github.com/openstax/cnx-recipes/issues/5251)

2023-10-17 14:54 UTC, jbwilson8 commented on styles/designs/carnival/parts/_table-components.scss
@kswanson33 @LostMojo I was able to use the `:last-child` pseudo selector in lieu of creating a new table component that targets the `rowspan.` This seemed like a much easier fix. If this issue arises again we can revisit the previously discussed idea of creating a table component for tables with rowspans.

2023-10-17 16:01 UTC, kswanson33 requested changes

2023-10-18 20:13 UTC, jbwilson8 commented on styles/designs/carnival/parts/_table-components.scss
>  $Table__Data--First: (
Thanks for the feedback! I was able to merge the redundant components and build all the books.

2023-10-18 20:59 UTC, kswanson33 requested changes

2023-10-18 20:59 UTC, kswanson33 commented on styles/designs/carnival/parts/_table-components.scss
>      _name: "FirstTableData",
oh, this name should probably be updated too 🙏 😅

2023-10-19 15:27 UTC, kswanson33 approved these changes

2023-10-20 03:01 UTC, merged